x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  disk-monitor:
    image: disk-monitor
    pull_policy: never
    build:
      context: ./disk-monitor
      args:
        DOCKER_TAG: ${PYTHON_IOPING_TAG:-3.12-slim}
    restart: unless-stopped
    <<: *logging

    ports:
      - "8000:8000"

    # Access to raw block devices
    privileged: true
    volumes:
      - /dev:/dev:ro

    command: ["python3", "disk-monitor.py", "--interval-seconds", "60"]

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/metrics"]
      interval: 60s
      timeout: 5s
      retries: 3

    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=8000

networks:
  default:
    enable_ipv6: ${IPV6:-false}
